Asset Metadata and sample data
pulibrary/tiger-data-app pull request #167
Opened 2023-08-31 18:03 UTC by hectorcorrea

Updated Asset Metadata section with an example on how to define and set a date field. 
Added script to initialize your local MF server with some sample data.

2023-08-31 20:41 UTC, hectorcorrea commented on docs/sandbox_data.md
> +    :element -name created_by    -type string             -min-occurs 1 -max-occurs 1 -label "User that created the project" >
Uses the pre-MVP fields indicated in Matt's document (https://docs.google.com/document/d/1XjXkzhs5ngM5cmyrmTLaIxG6TF4jT7-HMsMrjj3akRw/edit)

2023-08-31 20:42 UTC, hectorcorrea commented on docs/sandbox_data.md
> +
Sets the fields

2023-09-01 11:33 UTC, carolyncole requested changes
@hectorcorrea just a couple small changes that would have made my life easier trying to run the script

2023-09-01 11:33 UTC, carolyncole commented on docs/sandbox_data.md
> +# You can run it from within Aterm with a command as follows:
Local aterm (not a web aterm)
```suggestion
# You can run it from within Local Aterm (not a Web Aterm) with a command as follows:
```

2023-09-01 11:33 UTC, carolyncole commented on docs/sandbox_data.md
> +# script.execute :in file://full/path/to/tiger-data-app/docs/sandbox_data.md
```suggestion
# script.execute :in file://full/path/to/tiger-data-app/docs/sandbox_data.md
# 
# In the same aterm, to see the resultant collection with metadata run:
# asset.collection.list :namespace /tigerdata_ns02 :assets true
```

2023-09-01 13:59 UTC, hectorcorrea commented
@carolyncole I've accepted the changes and requested a re-review but it still shows as "changes requested" ¯\_(ツ)_/¯

2023-09-01 14:01 UTC, merged