drafting an ADR for the valid statuses of a project
pulibrary/tiger-data-app pull request #638
Opened 2024-04-12 17:39 UTC by JaymeeH

- ref #637

2024-04-12 20:29 UTC, carolyncole requested changes
Looks good.  Just a couple of small changes.

2024-04-12 20:29 UTC, carolyncole commented on spec/models/provenance_event_spec.rb
> +    it "makes a provenance event recording the status being set to pending" do
```suggestion
    it "makes a provenance event recording the status being set to approved" do
```

2024-04-12 20:29 UTC, carolyncole commented on spec/models/provenance_event_spec.rb
> +      pe.event_details = "The Status was updated from pending to approved"
```suggestion
      pe.event_details = "The Status was updated from approved to active"
```

2024-04-12 20:29 UTC, carolyncole commented on spec/models/provenance_event_spec.rb
> +      pe.event_details = "The Status was updated from pending to approved"
```suggestion
      pe.event_details = "The Status was updated from approved to active"
```

2024-04-15 11:44 UTC, bess commented
@carolyncole Thank you, good catch! Fixed.

2024-04-15 12:11 UTC, carolyncole approved these changes

2024-04-15 12:11 UTC, merged