Add configurable banner to the top of page
pulibrary/tiger-data-app pull request #701
Opened 2024-05-09 14:29 UTC by leefaisonr

Ref #695

2024-05-09 15:38 UTC, carolyncole requested changes
Love the use of sanitize.  I would love a bit of a reorg.  See suggested changes....

2024-05-09 15:38 UTC, carolyncole commented on app/views/shared/_banner.html.erb
> +    <%= sanitize @banner_title %>
I would love to see the `<h1>` here
```suggestion
    <h1><%= sanitize @banner_title %></h1>
```

2024-05-09 15:38 UTC, carolyncole commented on app/helpers/banner_helper.rb
> +    @banner_title = "<h1>#{@yaml_data[Rails.env]['title']}</h1>"
I would love it if the `<h1>` wen into the partial
```suggestion
    @banner_title = @yaml_data[Rails.env]['title']
```

2024-05-09 15:38 UTC, carolyncole commented on app/helpers/banner_helper.rb
> +    @banner_body = "<p>#{@yaml_data[Rails.env]['body']}</p>"
I would love it if the `<p>` went into the partial
```suggestion
    @banner_body = @yaml_data[Rails.env]['body']
```

2024-05-09 15:38 UTC, carolyncole commented on app/views/shared/_banner.html.erb
> +    <%= sanitize @banner_body, attributes: %w(href target)%>
```suggestion
   <p><%= sanitize @banner_body, attributes: %w(href target)%></p>
```

2024-05-09 15:38 UTC, carolyncole commented on app/helpers/banner_helper.rb
> +  # rubocop:enable Rails/ContentTag
If the tags were in the partial this would not be needed
```suggestion
```

2024-05-09 15:38 UTC, carolyncole commented on app/helpers/banner_helper.rb
> +  # rubocop:disable Rails/ContentTag
If the tags were in the partial this would not be needed
```suggestion
```

2024-05-09 17:33 UTC, leefaisonr commented
Thanks for the suggested edits, @carolyncole!

2024-05-10 12:14 UTC, carolyncole commented
close in favour of #706

2024-05-10 12:14 UTC, closed without merging