Ensuring that @project.metadata can be resolved within the view templates
pulibrary/tiger-data-app pull request #880
Opened 2024-08-06 19:18 UTC by jrgriffiniii

Resolves #877

2024-08-07 17:46 UTC, carolyncole requested changes
I wonder if this would be a good opportunity to utilize the ProjectMetadata object in the views.  https://github.com/pulibrary/tiger-data-app/blob/main/app/models/project_metadata.rb

Either way I think you atleast need the small change I suggested to avoid a nil pointer error

2024-08-07 17:46 UTC, carolyncole commented on app/controllers/projects_controller.rb
> +    @project_id = @project_metadata[:project_id]
Did you mean to default to an empty hash so the rest of the calls would not fail if the metadata was nil?
```suggestion
    @project_id = @project_metadata[:project_id] || { }
```

2024-08-12 15:04 UTC, jrgriffiniii commented
Thank you very much @carolyncole, this was the solution!

2024-08-12 15:06 UTC, carolyncole approved these changes

2024-08-12 15:07 UTC, merged